= Guided solution (page 2)

. Identify the OpenFlow number corresponding to the external network interface (eth2). This is important for later tracing.
+
[source, bash]
----
ovs-ofctl show br-ex
----
+
.Sample output
----
[root@compute02 ~]# ovs-ofctl show br-ex
OFPT_FEATURES_REPLY (xid=0x2): dpid:000052540002331f
n_tables:254, n_buffers:0
capabilities: FLOW_STATS TABLE_STATS PORT_STATS QUEUE_STATS ARP_MATCH_IP
actions: output enqueue set_vlan_vid set_vlan_pcp strip_vlan mod_dl_src mod_dl_dst mod_nw_src mod_nw_dst mod_nw_tos mod_tp_src mod_tp_dst
 1(eth2): addr:52:54:00:02:33:1f
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
 3(patch-provnet-8): addr:de:e9:22:1f:92:12
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
 LOCAL(br-ex): addr:52:54:00:02:33:1f
     config:     0
     state:      0
     speed: 0 Mbps now, 0 Mbps max
OFPT_GET_CONFIG_REPLY (xid=0x4): frags=normal miss_send_len=0
----
+
The interface eth2 is port 1 as denoted by *1(eth2)* in the above output.

. Use the identified OpenFlow number to trace the packet flow using the ovs-appctl command with the proto/trace tool.
+
[source, bash]
----
ovs-appctl ofproto/trace br-ex in_port=1 $(ovs-pcap icmp-request.pcap) | less
----
+
.Sample output
----
[root@compute02 ~]# ovs-appctl ofproto/trace br-ex in_port=1 $(ovs-pcap icmp-request.pcap) | less
Flow: icmp,in_port=1,vlan_tci=0x0000,dl_src=52:54:00:02:33:fe,dl_dst=fa:16:3e:42:c2:37,nw_src=172.25.250.9,nw_dst=192.168.51.194,nw_tos=0,nw_ecn=0,nw_ttl=63,nw_frag=no,icmp_type=8,icmp_code=0

bridge("br-ex")
---------------
 0. priority 0
    NORMAL
     -> no learned MAC for destination, flooding

bridge("br-int")
 0. in_port=6,vlan_tci=0x0000/0x1000, priority 100, cookie 0xecf8ffe
    set_field:0x5/0xffff->reg13
    set_field:0x2->reg11
    set_field:0x3->reg12
    set_field:0x1->metadata
    set_field:0x1->reg14
    set_field:0/0xffff0000->reg13
    resubmit(,8)

. . .
----
+
* As observed in the provided snippet, the packet trajectory involves passing through the br-ex bridge and utilizing the flow table 0.
* In this context, the process involves regular switching operations.
* The packet journey leads it to be forwarded to the br-int bridge.
* This action is facilitated via the in_port=8 (this might differ in your output), which corresponds to the patch port connecting br-ex and br-int.

. We can now run the same command with in_port=8 and pass the packet to br-int this time.
+
[source, bash]
----
ovs-appctl ofproto/trace br-int in_port=8 $(ovs-pcap icmp-request.pcap) | less
----
+
.Sample output
----
[root@compute02 ~]# ovs-appctl ofproto/trace br-int in_port=8 $(ovs-pcap icmp-request.pcap) | less
Flow: icmp,in_port=8,vlan_tci=0x0000,dl_src=52:54:00:02:33:fe,dl_dst=fa:16:3e:a7:e1:96,nw_src=172.25.250.9,nw_dst=192.168.51.170,nw_tos=0,nw_ecn=0,nw_ttl=63,nw_frag=no,icmp_type=8,icmp_code=0

bridge("br-int")
----------------
 0. in_port=8,vlan_tci=0x0000/0x1000, priority 100, cookie 0x8bb92bff
    set_field:0x8/0xffff->reg13
    set_field:0x7->reg11
    set_field:0x9->reg12
    set_field:0x1->metadata
    set_field:0x1->reg14
    set_field:0/0xffff0000->reg13
    resubmit(,8)
 8. metadata=0x1, priority 50, cookie 0xfcfd512c
    set_field:0/0x1000->reg10
    resubmit(,73)
    73. No match.
            drop
----

. Understand the significance of the metadata and reg14 fields in the tracing output. Metadata represents the datapath ID, and reg14 holds the identifier of the port in the Port_Bindings table.
+
----
    set_field:0x1->metadata
    set_field:0x1->reg14
----
+
Datapath in OVN represents a logical entity which can either be a switch or a router.

. Use ovsdbserver-sb POD to list the datapath bindings.
+
Run the below command on the workstation VM:
+
[source, bash]
----
oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only list datapath_binding
----
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only list datapath_binding
_uuid               : 1e76c039-73e8-4e9b-8259-c49f399f5878
external_ids        : {always_learn_from_arp_request="false", logical-router="b1a6d89d-38b4-4542-a9ca-747a7d0967d5", name=neutron-98e12907-fbbd-4f9c-a479-42b42e94d611, name2=scenario-bfx019-router}
load_balancers      : []
tunnel_key          : 3

_uuid               : e53c886d-6da3-4829-95a0-4068be40050b
external_ids        : {logical-switch="c96a9d53-7d7e-4bf6-8855-63600060b7aa", name=neutron-795607c7-30ae-4acf-9b83-ef207f17a781, name2=scenario-bfx019-network}
load_balancers      : []
tunnel_key          : 2

_uuid               : ae1a7b22-45fc-44e3-a4b1-ef4f2f7a4e46
external_ids        : {logical-switch="c919dbb1-f775-4ca1-9bde-351f7d14c2ef", name=neutron-eb22ba34-3201-467b-9ce2-451ee53790e9, name2=public}
load_balancers      : []
tunnel_key          : 1
----
+
In the above output:
+
* `tunnel_key 1` is a logical switch which maps to the Neutron network id `ee961465-e812-4563-aaa8-05adb3476889`
* Neutron network name is `public`. 
* A Logical switch in OVN is a network in Neutron. 
* Hence datapath 1 is the public switch in OVN.

. Match the tunnel key with the Datapath_Binding table to identify the logical switch (datapath) associated with the packet.
+
[source, bash]
----
oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only find datapath_binding tunnel_key=1
----
+
Make sure you are using correct tunnel_key
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only find datapath_binding tunnel_key=1
_uuid               : ae1a7b22-45fc-44e3-a4b1-ef4f2f7a4e46
external_ids        : {logical-switch="c919dbb1-f775-4ca1-9bde-351f7d14c2ef", name=neutron-eb22ba34-3201-467b-9ce2-451ee53790e9, name2=public}
load_balancers      : []
tunnel_key          : 1
----

. By searching for the Port_Binding that contains the datapath of interest, it is possible to determine the incoming port that holds this key. This combination of the tunnel key and the associated datapath (identified through _uuid) uniquely identifies the port within the network environment.
+
[source, bash]
----
oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only find Port_Binding datapath=UUID
----
+
**Replace appropriate string for UUID.**
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl --no-leader-only find Port_Binding datapath=ae1a7b22-45fc-44e3-a4b1-ef4f2f7a4e46
----

. Look for the port binding that has tunnel key 1 in the output of the above command.
+
----
...
_uuid               : 8bb92bff-5354-4bea-b04e-8e3ec2f7b6af
additional_chassis  : []
additional_encap    : []
chassis             : []
datapath            : ae1a7b22-45fc-44e3-a4b1-ef4f2f7a4e46
encap               : []
external_ids        : {}
gateway_chassis     : []
ha_chassis_group    : []
logical_port        : provnet-83c416fc-6495-44e9-af91-974e17bb8562
mac                 : [unknown]
mirror_rules        : []
nat_addresses       : []
options             : {localnet_learn_fdb="false", mcast_flood="false", mcast_flood_reports="true", network_name=datacentre}
parent_port         : []
port_security       : []
requested_additional_chassis: []
requested_chassis   : []
tag                 : []
tunnel_key          : 1
type                : localnet
up                  : false
virtual_parent      : []
. . .
----
+
* This means the incoming port is the port with `tunnel_key 1` on data path `ae1a7b22-45fc-44e3-a4b1-ef4f2f7a4e46`.
* These two numbers uniquely identify the port in the environment.
* We can now see how the packet is being processed in the pipeline.

. Re-run the previous ovs-appctl command **on the compute node** and scroll through the output.
+
[source, bash]
----
ovs-appctl ofproto/trace br-int in_port=8 $(ovs-pcap icmp-request.pcap) | less
----
+
.Sample output
----
[root@compute02 ~]# ovs-appctl ofproto/trace br-int in_port=8 $(ovs-pcap icmp-request.pcap) | less
. . .
    set_field:0x3->metadata
. . . 
bridge("br-int")
----------------
    thaw
        Resuming from table 13
13. metadata=0x3, priority 0, cookie 0x8fced113
    resubmit(,14)
14. metadata=0x3, priority 0, cookie 0x7615a127
    resubmit(,15)
15. ip,reg14=0x1,metadata=0x3,nw_dst=192.168.51.170, priority 100, cookie 0x832d5779
    ct(commit,table=16,zone=NXM_NX_REG11[0..15],nat(dst=192.168.110.191))
    nat(dst=192.168.110.191)
     -> A clone of the packet is forked to recirculate. The forked pipeline will be resumed at table 16.
     -> Sets the packet to an untracked state, and clears all the conntrack fields.

Final flow: recirc_id=0x87,eth,icmp,reg0=0xfa16,reg1=0x3e602330,reg9=0x4,reg11=0x1,reg12=0x4,reg14=0x1,metadata=0x3,in_port=8,vlan_tci=0x0000,dl_src=52:54:00:02:33:fe,dl_dst=fa:16:3e:a7:e1:96,nw_src=172.25.250.9,nw_dst=192.168.51.170,nw_tos=0,nw_ecn=0,nw_ttl=63,nw_frag=no,icmp_type=8,icmp_code=0
Megaflow: recirc_id=0x87,eth,ip,in_port=8,nw_dst=192.168.51.170,nw_frag=no
Datapath actions: ct(commit,zone=1,nat(dst=192.168.110.191)),recirc(0x88)

. . .
----
+
* The metadata field `0x3` in the above output could be different for you as the packet would be going through different logical entities in the network.
* Scroll down and see the NAT rule applied which does the conversion from floating ip (192.168.51.170) to fixed ip (192.168.110.191).
* The IP addresses would be as per your environment.

. Continue to scroll down at the bottom and observe the drop rule on table 44
+
.Sample output
----
        44. ip,reg0=0x1/0x1,metadata=0x2, priority 100, cookie 0xe4818076
            ct(table=45,zone=NXM_NX_REG13[0..15])
            drop
             -> A clone of the packet is forked to recirculate. The forked pipeline will be resumed at table 45.
             -> Sets the packet to an untracked state, and clears all the conntrack fields.
----

. Continue to scroll till the end and observe the final rule with the set_field actions at table 47.
+
.Sample output
----
. . . 
bridge("br-int")
----------------
    thaw
        Resuming from table 45
45. ct_state=+new-est+trk,metadata=0x2, priority 7, cookie 0x17340a6f
    set_field:0x80000000000000000000000000/0x80000000000000000000000000->xxreg0
    set_field:0x200000000000000000000000000/0x200000000000000000000000000->xxreg0
    resubmit(,46)
46. ip,reg0=0x200/0x200,reg15=0x3,metadata=0x2, priority 2001, cookie 0x9c9f8587
    set_field:0x2000000000000/0x2000000000000->xreg4
    resubmit(,47)
47. reg8=0x20000/0x20000,metadata=0x2, priority 1000, cookie 0x50ece857
    set_field:0/0x1000000000000->xreg4
    set_field:0/0x2000000000000->xreg4
    set_field:0/0x4000000000000->xreg4

Final flow: recirc_id=0x8f,ct_state=new|trk,ct_zone=5,eth,icmp,reg0=0x281,reg11=0x3,reg12=0x2,reg13=0x5,reg14=0x2,reg15=0x3,metadata=0x2,in_port=ANY,vlan_tci=0x0000,dl_src=fa:16:3e:48:0b:45,dl_dst=fa:16:3e:f4:87:d1,nw_src=172.25.250.9,nw_dst=192.168.110.191,nw_tos=0,nw_ecn=0,nw_ttl=62,nw_frag=no,icmp_type=8,icmp_code=0
Megaflow: recirc_id=0x8f,ct_state=+new-est-rel-rpl-inv+trk,ct_mark=0/0x1,eth,icmp,in_port=ANY,dl_src=fa:16:3e:48:0b:45,nw_frag=no
Datapath actions: drop
----
+
* The cookie value (in this case 0x50ece857), is significant as it represents a logical flow within OVN. 
* Logical flows are internal constructs within the Southbound database that describe how packets would be processed within the OVN infrastructure. 
* These logical flows serve as the basis upon which actual OpenFlows are constructed and enforced.

. To continue investigating, return to the workstation and list the Southbound logical flows.
+
----
oc exec -n openstack $(oc get pods -n openstack -l service=ovsdbserver-sb -o name | head -n 1) -- ovn-sbctl list Logical_Flow | less
----
+
In the list of logical flows, search for the cookie value noted earlier but without the leading 0x (in this case, 50ece857). This allows you to pinpoint the specific logical flow associated with the packet in question.

. Note that the logical flow includes references to a flow uuid that ties back to the previously identified cookie.
+
----
_uuid               : 50ece857-3056-4847-845e-3cd96aa7e62c
actions             : "reg8[16] = 0; reg8[17] = 0; reg8[18] = 0; /* drop */"
controller_meter    : []
external_ids        : {source="northd.c:6695", stage-name=ls_out_acl_action}
logical_datapath    : e53c886d-6da3-4829-95a0-4068be40050b
logical_dp_group    : []
match               : "reg8[17] == 1"
pipeline            : egress
priority            : 1000
table_id            : 5
tags                : {}
hash                : 0
----
+
* Observe the `stage-name=ls_out_acl` parameter within the logical flow. 
* This indicates that the logical flow resides in the stage called **logical switch out acl**. 
* In the context of OVN, ACLs (Access Control Lists) play a crucial role in implementing security groups. 
* The specific logical flow being examined appears to relate to egress traffic, as indicated by the `pipeline` designation `egress`.
+
FIXME: below differs in the output
+
* Additionally, the match parameter points to the condition outport neutron_pg_drop && ip, specifying that the action is to drop packets. 
* It is important to understand that neutron_pg_drop refers to an internal concept in Neutron, which is the networking component in OpenStack. 
* This signifies that packets matching this condition are dropped by default. 
* Within Neutron, to allow specific traffic through a security group, you must define rules that explicitly let it. 
* If no such rules exist, traffic would be subject to default actions like the one represented by neutron_pg_drop, resulting in packet drops.

. List the ports associated with the instance. 
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack port list --server scenario-bfx019-vm
----
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port list --server scenario-bfx019-vm
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                             | Status |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| d0280d77-d8ae-4561-82f4-6d6240eac0ed |      | fa:16:3e:f4:87:d1 | ip_address='192.168.110.191', subnet_id='a2084f94-58a2-4c83-aff5-a78be643ee49' | ACTIVE |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
----

. Run openstack port show on the relevant port ID.
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack port show <port ID>
----
+
**Replace <port ID> with appropriate string.**
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port show d0280d77-d8ae-4561-82f4-6d6240eac0ed
+-------------------------+-------------------------------------------------------------------------------------------------------------+
| Field                   | Value                                                                                                       |
+-------------------------+-------------------------------------------------------------------------------------------------------------+
| admin_state_up          | UP                                                                                                          |
| allowed_address_pairs   |                                                                                                             |
| binding_host_id         | compute02.srv.example.com                                                                                   |
| binding_profile         |                                                                                                             |
| binding_vif_details     | bound_drivers.0='ovn', bridge_name='br-int', connectivity='l2', datapath_type='system', port_filter='True'  |
| binding_vif_type        | ovs                                                                                                         |
| binding_vnic_type       | normal                                                                                                      |
| created_at              | 2025-06-04T17:39:52Z                                                                                        |
| data_plane_status       | None                                                                                                        |
| description             |                                                                                                             |
| device_id               | 164f92ed-8aa6-42fd-b862-43bc4d92e360                                                                        |
| device_owner            | compute:nova                                                                                                |
| device_profile          | None                                                                                                        |
| dns_assignment          | fqdn='scenario-bfx019-vm.openstackgate.local.', hostname='scenario-bfx019-vm', ip_address='192.168.110.191' |
| dns_domain              |                                                                                                             |
| dns_name                | scenario-bfx019-vm                                                                                          |
| extra_dhcp_opts         |                                                                                                             |
| fixed_ips               | ip_address='192.168.110.191', subnet_id='a2084f94-58a2-4c83-aff5-a78be643ee49'                              |
| id                      | d0280d77-d8ae-4561-82f4-6d6240eac0ed                                                                        |
| ip_allocation           | immediate                                                                                                   |
| mac_address             | fa:16:3e:f4:87:d1                                                                                           |
| name                    |                                                                                                             |
| network_id              | 795607c7-30ae-4acf-9b83-ef207f17a781                                                                        |
| numa_affinity_policy    | None                                                                                                        |
| port_security_enabled   | True                                                                                                        |
| project_id              | 7ac1618d984947c0bfcbf713a94fed4a                                                                            |
| propagate_uplink_status | None                                                                                                        |
| qos_network_policy_id   | None                                                                                                        |
| qos_policy_id           | None                                                                                                        |
| resource_request        | None                                                                                                        |
| revision_number         | 4                                                                                                           |
| security_group_ids      | 74e453b4-e25b-4bf0-81df-f464c2e6b141                                                                        |
| status                  | ACTIVE                                                                                                      |
| tags                    |                                                                                                             |
| trunk_details           | None                                                                                                        |
| updated_at              | 2025-06-04T17:39:59Z                                                                                        |
+-------------------------+-------------------------------------------------------------------------------------------------------------+
[student@workstation ~]$ 
----
+
* This step provides insight into the specific ports, their configurations, and their associated security groups, which is critical for resolving the packet drop issue.
* The port associated with the instance has the `port_security_enabled` flag set to `true`. 
* This signifies that port security mechanisms are active, enhancing the overall security of the network environment.
* Pay attention to the `security_group_ids` field in the port's output. 
* This field contains references to the associated security groups that govern the traffic allowed to and from the instance.

. Fetch detailed information about the security group.
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack security group show uuid
----
+
**Replace uuid with appropriate string.**
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack security group show 74e453b4-e25b-4bf0-81df-f464c2e6b141
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field           | Value                                                                                                                                                                        |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| created_at      | 2025-06-04T17:39:35Z                                                                                                                                                         |
| description     | scenario-bfx019-sg                                                                                                                                                           |
| id              | 74e453b4-e25b-4bf0-81df-f464c2e6b141                                                                                                                                         |
| name            | scenario-bfx019-sg                                                                                                                                                           |
| project_id      | 7ac1618d984947c0bfcbf713a94fed4a                                                                                                                                             |
| revision_number | 1                                                                                                                                                                            |
| rules           | created_at='2025-06-04T17:39:35Z', direction='egress', ethertype='IPv6', id='626d96bc-67cb-45ed-8976-cb6143da7306', standard_attr_id='66', updated_at='2025-06-04T17:39:35Z' |
|                 | created_at='2025-06-04T17:39:35Z', direction='egress', ethertype='IPv4', id='f32ee870-94de-4ffe-af1b-094b36c863ef', standard_attr_id='69', updated_at='2025-06-04T17:39:35Z' |
| shared          | False                                                                                                                                                                        |
| stateful        | True                                                                                                                                                                         |
| tags            | []                                                                                                                                                                           |
| updated_at      | 2025-06-04T17:39:35Z                                                                                                                                                         |
+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[student@workstation ~]$ 
----
+
* Upon inspecting the rules of the associated security group, it becomes evident that the current rules primarily let egress traffic. 
* However, in this case, the instance requires ingress traffic access for both SSH and ICMP, which is lacking in the existing ruleset. 
* The absence of rules allowing this specific ingress traffic results in the drop of the incoming packets.

. The resolution involves adding the necessary rules to the security group let the required SSH and ICMP traffic. 
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack security group rule create --ingress --protocol icmp uuid
oc exec -n openstack openstackclient -- openstack security group rule create --ingress --protocol tcp --dst-port 22 uuid
----
+
* **Replace uuid with the appropriate string.**
* These rules would specify the allowed protocols, ports, and sources/destinations for the traffic.
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack security group rule create --ingress --protocol icmp 74e453b4-e25b-4bf0-81df-f464c2e6b141
+-------------------------+--------------------------------------+
| Field                   | Value                                |
+-------------------------+--------------------------------------+
| created_at              | 2025-06-09T06:03:45Z                 |
| description             |                                      |
| direction               | ingress                              |
| ether_type              | IPv4                                 |
| id                      | abcef87f-7819-4550-bb82-5fbc8b9278d0 |
| name                    | None                                 |
| normalized_cidr         | 0.0.0.0/0                            |
| port_range_max          | None                                 |
| port_range_min          | None                                 |
| project_id              | 7ac1618d984947c0bfcbf713a94fed4a     |
| protocol                | icmp                                 |
| remote_address_group_id | None                                 |
| remote_group_id         | None                                 |
| remote_ip_prefix        | 0.0.0.0/0                            |
| revision_number         | 0                                    |
| security_group_id       | 74e453b4-e25b-4bf0-81df-f464c2e6b141 |
| tags                    | []                                   |
| updated_at              | 2025-06-09T06:03:45Z                 |
+-------------------------+--------------------------------------+
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack security group rule create --ingress --protocol tcp --dst-port 22 74e453b4-e25b-4bf0-81df-f464c2e6b141
+-------------------------+--------------------------------------+
| Field                   | Value                                |
+-------------------------+--------------------------------------+
| created_at              | 2025-06-09T06:04:08Z                 |
| description             |                                      |
| direction               | ingress                              |
| ether_type              | IPv4                                 |
| id                      | 96bb3448-970b-404f-b6f0-ad5daabce36c |
| name                    | None                                 |
| normalized_cidr         | 0.0.0.0/0                            |
| port_range_max          | 22                                   |
| port_range_min          | 22                                   |
| project_id              | 7ac1618d984947c0bfcbf713a94fed4a     |
| protocol                | tcp                                  |
| remote_address_group_id | None                                 |
| remote_group_id         | None                                 |
| remote_ip_prefix        | 0.0.0.0/0                            |
| revision_number         | 0                                    |
| security_group_id       | 74e453b4-e25b-4bf0-81df-f464c2e6b141 |
| tags                    | []                                   |
| updated_at              | 2025-06-09T06:04:08Z                 |
+-------------------------+--------------------------------------+
[student@workstation ~]$ 
----
