= Guided solution (page 1)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Platform.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and then step through the fix.
+
____
[student@workstation ~]$ ssh stack@director
[stack@director ~]$ source overcloudrc
(overcloud) [stack@director ~]$ lab start bfx019
Running start action against scenario bfx019
Run the following command:
ssh -i /home/stack/osp_training/.scenariobfx019/scenario-bfx019-key.pem cirros@172.25.250.203
____

2. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
+
____
(overcloud) [stack@director ~]$ ssh -i /home/stack/osp_training/.scenariobfx019/scenario-bfx019-key.pem cirros@172.25.250.203
*
ssh: connect to host 172.25.250.203 port 22: Connection timed out

(overcloud) [stack@director ~]$ *ping 172.25.250.203 -c 1
PING 172.25.250.203 (172.25.250.203) 56(84) bytes of data.

--- 172.25.250.203 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
____
+
You observe that both ping and ssh attempts failed which indicates lack of connectivity.

3. Access the overcloud environment and determine the specific compute node where the instance is currently running.
+
____
(overcloud) [stack@director ~]$ openstack server list --long -c Name -c Status -c Host
+--------------------+--------+-------------------------------------+
| Name               | Status | Host                                |
+--------------------+--------+-------------------------------------+
| scenario-bfx019-vm | ACTIVE | overcloud-novacompute-1.localdomain |
+--------------------+--------+-------------------------------------+
____
+
Observe that it is overcloud-novacompute-1 in the above output, it my differ in your case.

4. Make sure you have access to compute node from other terminal before proceeding further.
+
____
(overcloud) [stack@director ~]$ ssh tripleo-admin@overcloud-compute1
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Sat Mar 16 09:49:27 2024 from 172.25.249.11
[tripleo-admin@overcloud-novacompute-1 ~]$
____
+
Note the slight change in the compute node's hostname for ssh connectivity.

5. Check the route taken to reach the instance from the director VM.
+
____
(overcloud) [stack@director ~]$ ip route get 172.25.250.203
172.25.250.203 dev eth0 src 172.25.250.11 uid 1003
____
+
The above output shows that the route goes through eth0.

6. Confirm that the director VM and the instance's floating IP are on the same Layer 2 (L2) domain, specifically on the 172.25.250.0 subnet.
+
____
(overcloud) [stack@director ~]$ ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:04:fa:0b brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 172.25.250.11/24 brd 172.25.250.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe04:fa0b/64 scope link
       valid_lft forever preferred_lft forever
____

7. Examine the ARP cache on the director VM.
+
____
(overcloud) [stack@director ~]$ ip neighbor | grep 172.25.250.203
172.25.250.203 dev eth0 lladdr fa:16:3e:60:74:ec STALE
____
+
* An entry with the floating IP is associated with a MAC address, indicating successful ARP negotiation.
* This signifies functional communication via ARP, but ICMP communication remains problematic.

8. Let us proceed to check whether the packets are being correctly routed to the appropriate node. Run the below command on the compute node to check the interface associated with the bridge br-ex.
+
____
(overcloud) [stack@director ~]$ ssh tripleo-admin@overcloud-compute0
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Feb  5 10:54:20 2024 from 172.25.249.11
[tripleo-admin@overcloud-novacompute-0 ~]$ sudo -i
[root@overcloud-novacompute-0 ~]# ovs-vsctl show
1943688a-c727-41a4-b37e-21ae1365b65d
    Manager "ptcp:6640:127.0.0.1"
        is_connected: true
    Bridge br-ex
        fail_mode: standalone
        Port br-ex
            Interface br-ex
                type: internal
        Port patch-provnet-7b11bd78-649c-49b7-a08d-bd11c75bd41a-to-br-int
            Interface patch-provnet-7b11bd78-649c-49b7-a08d-bd11c75bd41a-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-7b11bd78-649c-49b7-a08d-bd11c75bd41a}
        Port ens4
            Interface ens4
____

9. To verify incoming traffic, initiate a tcpdump on this interface on the compute node and try to ping the instance from another terminal from the director node.
+
____
[root@overcloud-novacompute-0 ~]# tcpdump -envvi ens4 icmp
dropped privs to tcpdump
tcpdump: listening on ens4, link-type EN10MB (Ethernet), snapshot length 262144 bytes
11:13:36.847633 52:54:00:04:fa:0b > fa:16:3e:60:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 20399, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.203: ICMP echo request, id 2, seq 1, length 64
11:13:37.867835 52:54:00:04:fa:0b > fa:16:3e:60:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 20599, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.203: ICMP echo request, id 2, seq 2, length 64
11:13:38.891757 52:54:00:04:fa:0b > fa:16:3e:60:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 20848, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.203: ICMP echo request, id 2, seq 3, length 64
11:13:39.915886 52:54:00:04:fa:0b > fa:16:3e:60:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 21512, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.203: ICMP echo request, id 2, seq 4, length 64
____
+
* You observe that ICMP echo requests arriving at the machine.
* The presence of ICMP echo requests reaching the external NIC on the compute node indicates the proper functioning of the Distributed Virtual Router (DVR).
* However, you observed that echo requests are not receiving the echo replies on the director VM.