= Break-fix Scenario

Objectives:

* Investigate the instance connectivity issue in Red Hat OpenStack Platform.

* Solve the instance connectivity in the hands-on lab environment.

Scenario: 

Your team manages a Red Hat OpenStack Platform (RHOSP) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is connectivity issue with instance running in OpenStack envrionment.

They noticed the following error:

----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx019/scenario-bfx019-key.pem cirros@192.168.51.194
ssh: connect to host 192.168.51.194 port 22: Connection timed out
----


== Recreate scenario

* Recreate this scenario by running the `lab` script on director VM as stack user:
----
[student@workstation ~]$ oc login -u admin -p redhatocp https://api.ocp4.example.com:6443
Login successful.

You have access to 76 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "openstack".

[student@workstation ~]$ lab start bfx019
Running start action against scenario bfx019
Run the following command:
ssh -i /home/student/osp_training/.scenariobfx019/scenario-bfx019-key.pem cirros@192.168.51.194
----

In the preceding output, ip address can differ in your lab environemnt.

- This breaks the connectivity to instance.

- To ensure scenario is recreated, run the ssh command from the previous output:
----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx019/scenario-bfx019-key.pem cirros@192.168.51.194
ssh: connect to host 192.168.51.194 port 22: Connection timed out
----



FIXME: accommodate below steps:
To run any of the break/fix scenarios in this repo you need to:

clone repository
$ mkdir osp_training
$ cd osp_training
$ git clone https://github.com/cubeek/osp-workshop-2022.git scenarios_repo
$ cd scenarios_repo
prepare inventory file for Ansible:
$ bash osp-workshop-2024.sh -s dataplanenodeset-openstack-data-plane -c ~/.auth/ocp4-kubeconfig inventory
now You can run scenarios with command like:
$ ./lab start bfx019
